"use client";
import { Geist, Geist_Mono } from "next/font/google";
import { useRouter } from "next/navigation";
import "./common.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const router = useRouter();

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      <nav className="navbar">
            <div id="logo">SMARTDEPLOY</div>
            <div id="nav-buttons">
              <button onClick={() => router.push("/home")}>Home</button>
              <button onClick={() => router.push("/dashboard")}>Dashboard</button>
              <button onClick={() => router.push("/responder")}>Responder</button>
            </div>
          </nav>

          <style jsx global>{`
          body, html {
            margin: 0;
            padding: 0;
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background-color: #121212;
            color: white;
          }
  
          .container {
            min-height: 100vh;
            background-color: #121212;
          }
  
          .navbar {
            background-color: #f2f2f2;
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 16px 32px;
          }
  
          .nav-buttons button {
            background: none;
            border: none;
            font-size: 16px;
            margin-left: 16px;
            cursor: pointer;
            padding: 8px 16px;
            color: #000;
          }
  
          .nav-buttons .active {
            background-color: #dcdcdc;
            border-radius: 8px;
            font-weight: 600;
          }
  
          .card-grid {
            display: grid;
            grid-template-columns: repeat(auto-fill, minmax(260px, 1fr));
            gap: 24px;
            padding: 40px;
          }
  
          .card {
            background-color: #000;
            border: 1px solid #2c2c2c;
            border-radius: 16px;
            padding: 24px;
            display: flex;
            flex-direction: column;
            justify-content: space-between;
          }
  
          .card-title {
            background-color: #2e2e2e;
            padding: 12px 16px;
            border-radius: 8px;
            font-size: 18px;
            margin-bottom: 16px;
          }
  
          .tag-label {
            font-weight: 500;
            margin-bottom: 8px;
          }
  
          .tags {
            display: flex;
            flex-wrap: wrap;
            gap: 10px;
          }
  
          .tag {
            background-color: #e10600;
            color: white;
            padding: 6px 16px;
            border-radius: 9999px;
            font-size: 14px;
            font-weight: 500;
          }
  
          .edit-button {
            align-self: flex-end;
            background-color: #2e2e2e;
            color: white;
            border: none;
            padding: 8px 16px;
            border-radius: 8px;
            margin-top: 20px;
            cursor: pointer;
          }
  
          .edit-button:hover {
            background-color: #3c3c3c;
          }
  
          .floating-button {
            position: fixed;
            bottom: 24px;
            right: 24px;
            width: 56px;
            height: 56px;
            font-size: 28px;
            border-radius: 50%;
            background-color: #2e2e2e;
            color: white;
            border: none;
            box-shadow: 0px 4px 12px rgba(0, 0, 0, 0.3);
            cursor: pointer;
          }
  
          .floating-button:hover {
            background-color: #3c3c3c;
          }
        `}</style>
  
  
        {children}
      </body>
    </html>
  );
}
